server:
  port: 8080
  
logging:
  level:
    root: ERROR
    #org.hibernate.orm.jdbc.bind: TRACE
    com.thiagoti.easypay: INFO

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:easypaydb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

springdoc:
  api-docs:
    path: /api-docs

app:
  external:
    transfer-authorizer:
      url: https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc
    notification:
      email:
        url: https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6
